.catalog:
  name: "Kafka Manager"
  version: 1.3.1.6-jbev1
  description: |
    Yahoo Kafka Manager.
  minimum_rancher_version: v1.1.3
  maintainer: "Jeff Kolb <jeff.kolb@intlfcstone.com>"
  uuid: kafka-man-0
  questions:
    - variable: "app_secret"
      description: "Application secret"
      label: "Application secret"
      required: true
      default: "letmein"
      type: "string"
    - variable: "km_args"
      description: "JVM arguments - Do not change this unless you know what you are doing!"
      label: "JVM arguments:"
      required: false
      default: "-Djava.net.preferIPv4Stack=true"
      type: "string"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use.
      label: "Zookeeper stack/service"
      default: "zookeeper/zk"
      required: true
      type: "service"
    - variable: "kafka_link"
      description: |
        Choose the Kafka service to use.
      label: "Kafka stack/service"
      default: "kafka/broker"
      required: true
      type: "service"

kafka-manager:
  scale: 1
  retain_ip: true
  health_check:
    port: 9000
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2